#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_summaries.py - Embed the curated offline fallback summaries into summaries.js.

Reads app/generated_summaries/<patientId>__<kind>.md (kind in summary|letter|instructions)
and writes app/summaries.js as `window.MS_SUMMARIES = { id: { kind: "<markdown>" } }`.

This keeps the human-readable .md files as the editable source of truth while letting
the app load the content offline (file:// safe, no fetch). Stdlib only.

Run:  python3 app/build_summaries.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "generated_summaries")
VALID_KINDS = {"summary", "letter", "instructions"}


def main():
    data = {}
    for fn in sorted(os.listdir(SRC)):
        if not fn.endswith(".md") or "__" not in fn:
            continue
        pid, rest = fn[:-3].split("__", 1)
        kind = rest
        if kind not in VALID_KINDS:
            continue
        with open(os.path.join(SRC, fn), encoding="utf-8") as f:
            content = f.read().strip()
        data.setdefault(pid, {})[kind] = content

    # Written to BOTH UI versions (app/ classic, n2/ redesigned).
    root = os.path.dirname(HERE)
    targets = [os.path.join(HERE, "summaries.js"),
               os.path.join(root, "n2", "summaries.js")]
    for out in targets:
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            f.write("// AUTO-GENERATED by app/build_summaries.py - do not edit by hand.\n")
            f.write("// Curated offline fallback summaries (source: app/generated_summaries/*.md).\n")
            f.write("window.MS_SUMMARIES = ")
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write(";\n")

    n = sum(len(v) for v in data.values())
    print("OK - embedded %d curated documents for %d patients -> app/summaries.js + n2/summaries.js"
          % (n, len(data)))


if __name__ == "__main__":
    main()
